int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int actual_sqrt_recursion(int n, int i);
int is_prime_number(int n);
int real_prime(int n, int i);
int is_palindrome(char *s);
int _strilen_recursion(char *s);
int check_pali(char *s, int i, int len);
int wildcmp(char *s1, char *s2);
